import { useMemo,useState } from 'react';
import { assignments as initialAssignments,checkins as initialCheckins,letters,members,topics as initialTopics } from './data/demo';
import type { Checkin,Member,PrayerTopic,Tab } from './domain/types'; import { starPosition,upsertCheckin } from './domain/sky'; import { createAssignments,validateAssignments } from './domain/assignment'; import { isDevMode } from './services/auth';
type Theme='day'|'night'; const nav:{id:Tab;label:string;icon:string}[]=[{id:'home',label:'홈',icon:'⌂'},{id:'pray',label:'기도',icon:'◐'},{id:'sky',label:'밤하늘',icon:'✦'},{id:'mail',label:'우편함',icon:'◇'},{id:'profile',label:'내 정보',icon:'○'}]; const today='2026-07-18';

function Login({onLogin}:{onLogin:()=>void}){const[token,setToken]=useState('JOY-0718-DEMO');return <main className="login"><div className="login-stars"/><section className="login-copy"><div className="intro-sheep" role="img" aria-label="손을 흔드는 기니또 양"/><p className="eyebrow">JOYFULL SOUND</p><h1>함께 기도하는 시간,<br/><em>기니또</em></h1><p className="welcome-line">기도하러 왔구나~</p></section><section className="login-panel"><div className="dev-badge">DEV DEMO · 실제 개인정보 입력 금지</div><label htmlFor="invite">초대 코드</label><input id="invite" value={token} onChange={e=>setToken(e.target.value)} autoComplete="one-time-code"/><button className="primary" onClick={onLogin} disabled={!token.trim()}>데모 멤버로 시작하기</button><button className="kakao" disabled>카카오로 계속하기 <small>연동 준비 중</small></button><p className="fine">운영에서는 관리자 초대와 카카오 계정이 한 번만 연결됩니다.</p></section></main>}

type GuideVariant='wave'|'pray'|'letter'|'celebrate';
function SheepGuide({variant,title,description}:{variant:GuideVariant;title:string;description:string}){return <aside className={`sheep-guide ${variant}`} aria-label="화면 안내"><div className="sheep-pose" role="img" aria-label="기니또 양 캐릭터"/><div><strong>{title}</strong><p>{description}</p></div></aside>}
const guides:Record<Tab,{variant:GuideVariant;title:string;description:string}>={
  home:{variant:'wave',title:'오늘의 기니또를 만나볼까?',description:'기도로 품을 한 사람과 새로 나눈 마음을 확인해 봐.'},
  pray:{variant:'pray',title:'천천히 읽고 함께 기도하자',description:'기도제목을 읽은 뒤 잠시 머물러도 좋아.'},
  sky:{variant:'celebrate',title:'함께 기도한 마음이 모였어',description:'이름은 보이지 않아도 기도의 흔적은 이곳에 남아.'},
  mail:{variant:'letter',title:'따뜻한 마음이 도착했어',description:'익명으로 건넨 응원과 기도를 이곳에서 만나봐.'},
  profile:{variant:'pray',title:'함께 기도받고 싶은 마음을 나눠줘',description:'내 기도제목은 나와 현재 기니또만 볼 수 있어.'}
};

function Shell(){const[tab,setTab]=useState<Tab>('home');const[theme,setTheme]=useState<Theme>(()=>{const h=new Date().getHours();return h>=6&&h<18?'day':'night'});const[composeTo,setComposeTo]=useState<Member|null>(null);const[checkins,setCheckins]=useState<Checkin[]>(initialCheckins);const[topics,setTopics]=useState<PrayerTopic[]>(initialTopics);const[toast,setToast]=useState('');const[preview,setPreview]=useState(initialAssignments);const me=members[0];const assignment=initialAssignments.find(a=>a.giverId===me.id)!;const target=members.find(m=>m.id===assignment.targetId)!;const targetTopics=topics.filter(t=>t.ownerId===target.id&&!t.isCompleted);const myTopics=topics.filter(t=>t.ownerId===me.id);const todayCheckins=checkins.filter(c=>c.date===today);const myCheckin=todayCheckins.find(c=>c.memberId===me.id);function notify(message:string){setToast(message);window.setTimeout(()=>setToast(''),2400)}function checkin(){setCheckins(v=>upsertCheckin(v,me.id,today,new Date().toISOString()));notify(myCheckin?'같은 별이 조금 더 밝아졌어요.':'오늘 밤하늘에 익명의 별이 생겼어요.');}
return <div className={`app-shell theme-${theme}`}><header><div><p className="eyebrow">7월의 기니또 · D-43</p><h1>{tab==='home'?`평안한 하루예요, ${me.name}님`:nav.find(n=>n.id===tab)?.label}</h1></div><div className="header-actions"><button className="theme-toggle" aria-label={theme==='day'?'밤 테마 미리보기':'낮 테마 미리보기'} onClick={()=>setTheme(theme==='day'?'night':'day')}>{theme==='day'?'☀':'☾'}</button><button className="avatar" aria-label="내 정보" onClick={()=>setTab('profile')}>{me.initial}</button></div></header><div className="demo-strip">샘플 데이터로 보는 DEV DEMO</div><main className="content"><SheepGuide {...guides[tab]}/>{tab==='home'&&<Home theme={theme} target={target.name} topics={targetTopics} checked={!!myCheckin} onPray={()=>setTab('pray')} onSky={()=>setTab('sky')}/>} {tab==='pray'&&<Pray name={target.name} avatarUrl={target.avatarUrl} onWrite={()=>{setComposeTo(target);setTab('mail')}} topics={targetTopics} count={myCheckin?.count??0} onCheckin={checkin}/>} {tab==='sky'&&<Sky checkins={todayCheckins} theme={theme}/>} {tab==='mail'&&(composeTo?<LetterComposer recipient={composeTo} onClose={()=>setComposeTo(null)} notify={notify}/>:<Mail meId={me.id}/>)} {tab==='profile'&&<Profile topics={myTopics} setTopics={setTopics} preview={preview} setPreview={setPreview} notify={notify}/>}</main><nav className="bottom-nav" aria-label="주요 메뉴">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>setTab(n.id)}><span>{n.icon}</span>{n.label}</button>)}</nav>{toast&&<div className="toast" role="status">{toast}</div>}</div>}

function Home({theme,target,topics,checked,onPray,onSky}:{theme:Theme;target:string;topics:PrayerTopic[];checked:boolean;onPray:()=>void;onSky:()=>void}){return <><section className="hero"><div className="moon"/><div className="hero-stars">✦　·　✧</div><p>오늘 내가 품을 한 사람</p><h2>{target}</h2><p className="soft">기도는 말보다 먼저 마음을 건네는 일이니까요.</p><button className="primary glow" onClick={onPray}>{checked?'오늘도 이어서 기도하기':'기도하러 가기'} <span>→</span></button></section><section><div className="section-head"><div><p className="eyebrow">LATEST PRAYER</p><h2>새로운 기도제목</h2></div><button className="text-btn" onClick={onPray}>모두 보기</button></div>{topics.slice(0,1).map(t=><article className="card prayer-card" key={t.id}><span className="quote">“</span><p>{t.body}</p><small>{t.createdAt.replaceAll('-','.')} 업데이트</small></article>)}</section><button className="sky-preview" onClick={onSky}><span>✦</span><div><strong>{theme==='day'?`오늘, ${initialCheckins.length}마리의 양이 모였어요`:`오늘 밤, ${initialCheckins.length}개의 마음이 빛났어요`}</strong><small>{theme==='day'?'이름 없이 함께 머무는 기도의 초장':'이름 없이 함께 만든 기도의 밤하늘'}</small></div><b>→</b></button></>}

function Pray({name,avatarUrl,topics,count,onCheckin,onWrite}:{name:string;avatarUrl?:string;topics:PrayerTopic[];count:number;onCheckin:()=>void;onWrite:()=>void}){const[index,setIndex]=useState(0);const topic=topics[index%Math.max(topics.length,1)];return <section className="pray-page"><div className="prayer-avatar">{avatarUrl?<img src={avatarUrl} alt={`${name}님의 프로필`}/>:<span>{name.slice(0,1)}</span>}</div><p className="eyebrow">오늘 내가 기도할 사람</p><h2>{name}</h2><p className="counter">기도제목 {topics.length?index+1:0} / {topics.length}</p><article className="focus-card"><span className="quote">“</span><p>{topic?.body??'아직 등록된 기도제목이 없어요. 마음에 떠오르는 기도로 함께해 주세요.'}</p></article>{topics.length>1&&<button className="secondary" onClick={()=>setIndex(v=>(v+1)%topics.length)}>다음 기도제목</button>}<button className="write-letter" onClick={onWrite}>◇ {name}에게 편지 쓰기</button><div className="quiet-line"><span/>잠시 머물러 기도해 보세요<span/></div><button className="primary complete" onClick={onCheckin}>✦　기기완!{count>0&&<small>오늘 {count}번째 마음을 이어가요</small>}</button><p className="fine">완료 기록은 이름 없이 밤하늘의 별로만 보여요.</p></section>}

function Sky({checkins,theme}:{checkins:Checkin[];theme:Theme}){const all=checkins.length===members.length;return <section className={`sky-page ${theme}`}><div className="sky-copy"><p className="eyebrow">2026. 07. 18</p><h2>{all?'오늘은 모두가 기도한 날이에요!':theme==='day'?'기도가 머무는 푸른 초장':'우리의 기도가 별이 되는 곳'}</h2><p>누가 기도했는지는 알 수 없어요.<br/>다만 서로를 향한 마음이 여기 남아요.</p></div><div className={'night-sky '+theme+' '+(all?'celebrate':'')}>{checkins.map(c=>{const p=starPosition(c.date,c.publicId);return <i key={c.publicId} className={`star level-${c.count}`} style={{left:`${p.x}%`,top:`${p.y}%`,width:p.size,height:p.size,animationDelay:`${p.delay}s`}}/>})}<div className="horizon one"/><div className="horizon two"/></div><div className="sky-summary"><strong>{checkins.length}</strong><span>/ {members.length}{theme==='day'?'마리의 양':'개의 별'}</span><p>오늘 공동체원이 기도한 익명의 흔적이에요.</p></div><div className="activity-list">{[...checkins].reverse().slice(0,3).map(c=><div key={c.publicId}><span>{theme==='day'?'🐑':'✦'}</span><p><strong>{new Date(c.lastAt).toLocaleTimeString('ko-KR',{hour:'numeric',minute:'2-digit'})}</strong><small>한 공동체원이 기도했어요</small></p></div>)}</div></section>}

function LetterComposer({recipient,onClose,notify}:{recipient:Member;onClose:()=>void;notify:(message:string)=>void}){const[message,setMessage]=useState('');function send(){if(!message.trim())return;notify(`${recipient.name}님에게 익명 편지를 보냈어요.`);setMessage('');onClose()}return <section className="letter-composer"><button className="back-button" onClick={onClose}>← 우편함으로</button><div className="recipient"><div className="recipient-avatar">{recipient.avatarUrl?<img src={recipient.avatarUrl} alt=""/>:recipient.initial}</div><div><small>익명으로 편지를 보내요</small><h2>{recipient.name}에게</h2></div></div><label htmlFor="letter-message">전하고 싶은 마음</label><textarea id="letter-message" value={message} onChange={event=>setMessage(event.target.value)} placeholder="기도하며 떠오른 응원과 따뜻한 마음을 적어 주세요." maxLength={1000}/><div className="letter-meta"><span>보낸 사람의 이름은 표시되지 않아요.</span><span>{message.length} / 1000</span></div><button className="primary" disabled={!message.trim()} onClick={send}>익명 편지 보내기</button></section>}

function Mail({meId}:{meId:string}){const mine=letters.filter(l=>l.receiverId===meId);return <section><p className="lead">말하지 않아도 전해지는<br/>작은 마음들이 도착했어요.</p><div className="mail-tabs"><button className="active">받은 편지 {mine.length}</button><button>보낸 편지</button></div>{mine.length?mine.map(l=><article className="card mail" key={l.id}><div className="mail-icon">◇</div><div><small>나의 기니또가 보낸 익명 편지</small><p>{l.message}</p><time>{new Date(l.createdAt).toLocaleDateString('ko-KR')}</time></div></article>):<div className="empty"><span>◇</span><h3>아직 도착한 편지가 없어요</h3><p>마음은 천천히 도착하기도 해요.</p></div>}<button className="primary">익명 편지 쓰기</button></section>}

function Profile({topics,setTopics,preview,setPreview,notify}:{topics:PrayerTopic[];setTopics:React.Dispatch<React.SetStateAction<PrayerTopic[]>>;preview:typeof initialAssignments;setPreview:React.Dispatch<React.SetStateAction<typeof initialAssignments>>;notify:(s:string)=>void}){const[text,setText]=useState('');const valid=useMemo(()=>validateAssignments(members,preview),[preview]);function add(){if(!text.trim())return;setTopics(v=>[{id:crypto.randomUUID(),ownerId:members[0].id,body:text.trim(),isCompleted:false,createdAt:today},...v]);setText('');notify('기도제목을 안전하게 추가했어요.')}return <section><div className="profile-head"><div className="avatar large">민</div><div><h2>민서</h2><p>관리자 · 7월의 기니또</p></div></div><div className="section-head"><h2>내 기도제목</h2><span>{topics.filter(t=>!t.isCompleted).length}개 진행 중</span></div><div className="add-topic"><label htmlFor="new-topic">새 기도제목</label><textarea id="new-topic" value={text} onChange={e=>setText(e.target.value)} placeholder="함께 기도받고 싶은 내용을 적어 주세요" maxLength={500}/><button className="primary" onClick={add}>추가하기</button></div>{topics.map(t=><article className={'card topic '+(t.isCompleted?'done':'')} key={t.id}><p>{t.body}</p><button onClick={()=>setTopics(v=>v.map(x=>x.id===t.id?{...x,isCompleted:!x.isCompleted}:x))}>{t.isCompleted?'다시 열기':'기도 응답 · 완료'}</button></article>)}<details className="admin"><summary>관리자 · 시즌 및 배정</summary><p>2026년 7–8월 시즌 · {members.length}명</p><button className="secondary" onClick={()=>setPreview(createAssignments(members))}>새 배정 미리보기</button><p className={valid?'valid':'invalid'}>{valid?'✓ 본인 배정·중복·누락 없이 검증됨':'배정 검증이 필요합니다.'}</p><div className="assignment-list">{preview.slice(0,4).map(a=><span key={a.giverId}>{members.find(m=>m.id===a.giverId)?.name} → {members.find(m=>m.id===a.targetId)?.name}</span>)}</div><button className="primary" disabled={!valid} onClick={()=>notify('DEV DEMO에서는 DB에 확정하지 않아요.')}>배정 확정</button></details></section>}

export default function App(){const[loggedIn,setLoggedIn]=useState(false);if(!isDevMode)return <div className="config-error"><h1>연결 설정이 필요해요</h1><p>Supabase 환경 변수를 설정한 뒤 운영 인증을 연결해 주세요.</p></div>;return loggedIn?<Shell/>:<Login onLogin={()=>setLoggedIn(true)}/>}
